# Generated by Django 4.2.1 on 2023-05-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_subject_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Subject',
            new_name='subject',
        ),
    ]
