# Generated by Django 4.2.1 on 2023-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_subject_task_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
